# Generated by Django 5.2.4 on 2025-08-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Kullanıcı Bilgisi', 'verbose_name_plural': 'Kullanıcı Bilgileri'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
    ]
