# Generated by Django 5.2.4 on 2025-08-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
    ]
