# Generated by Django 5.2.4 on 2026-03-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_blogindexpage_contactmessage_galleryitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='product',
            name='features_es',
            field=models.TextField(blank=True, null=True, verbose_name='Ürün Özellikleri'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es',
            field=models.CharField(max_length=250, null=True, verbose_name='Ürün Adı'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Garanti Süresi'),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='question_text_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productquestionoption',
            name='option_text_es',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
