# Generated by Django 5.2.4 on 2025-08-05 16:02

import django.db.models.deletion
import image_cropping.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_employee_education_experience_jobinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('profile_image', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='İşlem Yapan Kullanıcı'),
        ),
    ]
