# Generated by Django 5.2.4 on 2025-08-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_employee_cropping_employee_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadın')], max_length=10, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif Mi?'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_images/', verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='İşe Başlama Tarihi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tc_identity',
            field=models.CharField(max_length=11, unique=True, verbose_name='TC Kimlik No'),
        ),
    ]
