# Generated by Django 5.2.4 on 2026-06-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_product_options_product_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmarketimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Ürün Market Görseli', 'verbose_name_plural': 'Ürün Market Görselleri'},
        ),
        migrations.AddField(
            model_name='productmarketimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
    ]
