# Generated by Django 5.2.4 on 2025-08-06 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_employee_address_alter_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_profile', to=settings.AUTH_USER_MODEL, verbose_name='İşlem Yapan Kullanıcı'),
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_profile', to=settings.AUTH_USER_MODEL, verbose_name='İşlem Yapan Kullanıcı'),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_profile', to=settings.AUTH_USER_MODEL, verbose_name='İşlem Yapan Kullanıcı'),
        ),
    ]
