# Generated by Django 5.2.4 on 2025-08-07 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_department_titlepersonel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_info', to='crm.department', verbose_name='Departman'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_info_as_employee', to='crm.employee'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_info_as_manager', to='crm.employee'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_info', to='crm.titlepersonel', verbose_name='Unvan'),
        ),
    ]
