# Generated by Django 5.2.4 on 2025-08-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_jobinfo_department_alter_jobinfo_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinfo',
            name='salary',
        ),
    ]
