# Generated by Django 5.2.4 on 2025-08-07 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_jobinfo_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Çalışma Lokasyonu Adı')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_location_profile', to=settings.AUTH_USER_MODEL, verbose_name='İşlem Yapan Kullanıcı')),
            ],
        ),
    ]
