# Generated by Django 5.2.4 on 2025-08-07 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_worklocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='work_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_info', to='crm.worklocation', verbose_name='Çalışma Lokasyonu'),
        ),
    ]
