# Generated by Django 5.2.4 on 2025-08-08 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_jobinfo_work_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_year',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Derece'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Okul Adı'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=255)),
                ('vergi_no', models.CharField(max_length=50, unique=True, verbose_name='Vergi Numarası / Kimlik Numarası')),
                ('telefon', models.CharField(blank=True, max_length=30, null=True)),
                ('telefon2', models.CharField(blank=True, max_length=30, null=True, verbose_name='İkinci Telefon')),
                ('fax', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='İkinci E-posta')),
                ('websitesi', models.URLField(blank=True, null=True)),
                ('adres', models.TextField(blank=True, null=True)),
                ('sehir', models.CharField(blank=True, max_length=100, null=True)),
                ('ilce', models.CharField(blank=True, max_length=100, null=True)),
                ('posta_kodu', models.CharField(blank=True, max_length=20, null=True)),
                ('kurulus_tarihi', models.DateField(blank=True, null=True)),
                ('calisan_sayisi', models.PositiveIntegerField(blank=True, null=True)),
                ('netciiro', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Net Ciro')),
                ('sektor_alt_bilgisi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sektör Alt Bilgisi')),
                ('yetkili_adi', models.CharField(blank=True, max_length=255, null=True)),
                ('yetkili_pozisyon', models.CharField(blank=True, max_length=255, null=True)),
                ('yetkili_telefon', models.CharField(blank=True, max_length=30, null=True)),
                ('yetkili_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('aktif_mi', models.BooleanField(default=True)),
                ('notlar', models.TextField(blank=True, null=True)),
                ('ulke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.country')),
                ('sektor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.sector')),
            ],
        ),
    ]
