# Generated by Django 5.2.4 on 2025-08-08 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_profile', to=settings.AUTH_USER_MODEL, verbose_name='İşlem Yapan Kullanıcı'),
        ),
        migrations.AddField(
            model_name='sector',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector_profile', to=settings.AUTH_USER_MODEL, verbose_name='İşlem Yapan Kullanıcı'),
        ),
    ]
