# Generated by Django 5.2.4 on 2025-08-10 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_company_facebook_alter_company_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(verbose_name='Ad')),
                ('last_name', models.CharField(verbose_name='Soyad')),
                ('unvan', models.CharField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('notlar', models.TextField(blank=True, null=True)),
                ('companyselection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Firma_Secimi', to='crm.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directorycompany_profile', to=settings.AUTH_USER_MODEL, verbose_name='İşlem Yapan Kullanıcı')),
            ],
        ),
    ]
