# Generated by Django 5.2.4 on 2025-08-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_directorycompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorycompany',
            name='tarihselection',
            field=models.DateField(blank=True, null=True, verbose_name='Tarih Seçimi'),
        ),
    ]
