# Generated by Django 5.2.4 on 2025-08-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_directorycompany_tarihselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorycompany',
            name='iletisimnedeni',
            field=models.CharField(blank=True, choices=[('teklif', 'Teklif Talebi'), ('destek', 'Destek Talebi'), ('bilgi', 'Bilgi İsteme'), ('is_ortakligi', 'İş Ortaklığı Talebi'), ('satis', 'Satış Temsilcisi Görüşmesi'), ('teknik', 'Teknik Destek'), ('musteri_hizmetleri', 'Müşteri Hizmetleri İletişimi'), ('odeme', 'Ödeme / Faturalandırma'), ('toplanti', 'Toplantı / Randevu Talebi'), ('referans', 'Referans / Tavsiye İsteği'), ('pazarlama', 'Pazarlama / Tanıtım Talebi'), ('diger', 'Diğer')], max_length=50, null=True, verbose_name='İletişim Nedeni'),
        ),
    ]
