# Generated by Django 5.2.4 on 2025-08-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_directorycompany_iletisimnedeni'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorycompany',
            name='bizi_nereden_buldu',
            field=models.CharField(blank=True, choices=[('internet', 'İnternet / Arama Motorları'), ('sosyal_medya', 'Sosyal Medya'), ('arkadas_tavsiye', 'Arkadaş / Tavsiye'), ('reklam', 'Reklam'), ('fuar', 'Fuar / Etkinlik'), ('diger', 'Diğer')], max_length=50, null=True, verbose_name='Bizi Nereden Buldu'),
        ),
    ]
