# Generated by Django 5.2.4 on 2025-08-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_directorycompany_bizi_nereden_buldu'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorycompany',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='directorycompany',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='directorycompany',
            name='bizi_nereden_buldu',
            field=models.CharField(blank=True, choices=[('bizulastik', 'Biz Ulaştık'), ('arama_motorlari', 'Arama Motorları'), ('internet', 'İnternet / Arama Motorları'), ('sosyal_medya', 'Sosyal Medya'), ('arkadas_tavsiye', 'Arkadaş / Tavsiye'), ('reklam', 'Reklam'), ('fuar', 'Fuar / Etkinlik'), ('diger', 'Diğer')], max_length=50, null=True, verbose_name='Bizi Nereden Buldu'),
        ),
    ]
