# Generated by Django 5.2.4 on 2025-08-12 11:34

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_directorycompany_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ürün Adı')),
                ('website_image', models.ImageField(blank=True, null=True, upload_to=crm.models.product_website_image_path, verbose_name='Web Sitesi Görseli')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to=crm.models.product_mobile_image_path, verbose_name='Mobil Görünüm Görseli')),
                ('offer_pdf', models.FileField(blank=True, null=True, upload_to=crm.models.product_offer_pdf_path, verbose_name='Fiyat Teklifi PDF')),
                ('features', models.TextField(blank=True, null=True, verbose_name='Ürün Özellikleri')),
                ('stock_code', models.CharField(max_length=50, unique=True, verbose_name='Stok Kodu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fiyat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Ağırlık (kg)')),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ölçüler (En x Boy x Yükseklik)')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Renk')),
                ('warranty_period', models.CharField(blank=True, max_length=50, null=True, verbose_name='Garanti Süresi')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Tanıtım Videosu URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='crm.category', verbose_name='Kategoriler')),
                ('related_products', models.ManyToManyField(blank=True, to='crm.product', verbose_name='İlgili Ürünler')),
            ],
        ),
    ]
