# Generated by Django 5.2.4 on 2025-08-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_remove_product_color_remove_product_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='yayinla',
            field=models.BooleanField(default=True, verbose_name='Yayınla'),
        ),
    ]
