# Generated by Django 5.2.4 on 2025-08-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_option_yayinla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_pdf',
        ),
    ]
