# Generated by Django 5.2.4 on 2025-08-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_remove_product_offer_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
    ]
