# Generated by Django 5.2.4 on 2025-08-14 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_remove_product_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Fırsat Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama / Notlar')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('in_progress', 'İşlemde'), ('won', 'Kazanıldı'), ('lost', 'Kaybedildi')], default='new', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=10, verbose_name='Öncelik')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Tahmini Değer')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Tahmini Kapanış Tarihi')),
                ('lead_source', models.CharField(blank=True, choices=[('referral', 'Referans'), ('website', 'Web Sitesi'), ('fair', 'Fuar'), ('social_media', 'Sosyal Medya'), ('other', 'Diğer')], max_length=50, null=True, verbose_name='Fırsatın Kaynağı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company', verbose_name='Firma')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.employee', verbose_name='Sorumlu Çalışan')),
                ('products', models.ManyToManyField(blank=True, to='crm.product', verbose_name='Ürünler')),
            ],
        ),
    ]
