"""
Django settings for liftkeys project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-03h*26-ff0gikg=qodz$^r#s9+55rw3o$0yu!dq-=7#1^5wu_j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False



ALLOWED_HOSTS = [
    '35.157.24.15',         # Sunucunun Dış IP'si (AWS Elastic IP vs)
    'liftkeys.com',       # Domainin (Varsa)
    'www.liftkeys.com',   # www versiyonu
    'localhost',          # Yerel erişim için
    '127.0.0.1'           # Yerel erişim için
]

CSRF_TRUSTED_ORIGINS = [
    'https://liftkeys.com',
    'https://www.liftkeys.com',
    'https://35.157.24.15'
]
# ALLOWED_HOSTS = ["*"]



# Application definition

INSTALLED_APPS = [
    # Çekirdek
    'django.contrib.sitemaps',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Medya / Resim
    'easy_thumbnails',
    'image_cropping',

    # Proje uygulamaları
    'crm',

    # Form ve widget destekleri
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',

    # Wagtail resmi uygulamalar
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.simple_translation",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "wagtail_localize",
    "wagtail_localize.locales",
    # Wagtail bağımlılıkları
    "modelcluster",
    "taggit",

    # Yeni eklediklerin
    "wagtailcache",
    "wagtail.contrib.table_block",

    # Çeviri Yönetimi
    'rosetta', # BURAYI EKLEDİK
]

WAGTAIL_SITE_NAME = "Liftkeys" 
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

if DEBUG:
    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.locale.LocaleMiddleware", # Dil algılama burada çalışır
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    ]
else:
    MIDDLEWARE = [
        # 1. Cache GÜNCELLEME (Response) - En başta olmalı
        "wagtailcache.cache.UpdateCacheMiddleware",

        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        
        # 2. Dil Algılama - Session'dan sonra, Common'dan önce
        "django.middleware.locale.LocaleMiddleware", 
        
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",

        # 3. Wagtail Yönlendirmeleri
        "wagtail.contrib.redirects.middleware.RedirectMiddleware",

        # 4. Cache GETİRME (Request) - En sonda olmalı
        "wagtailcache.cache.FetchFromCacheMiddleware",
    ]

AUTH_USER_MODEL = 'crm.CustomUser'

ROOT_URLCONF = 'liftkeys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'crm.context_processors.menu_context',
                'crm.context_processors.contact_form_context',
                "django.template.context_processors.request",
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'liftkeys.wsgi.application'



SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 gün (saniye cinsinden)
SESSION_SAVE_EVERY_REQUEST = True  # her request'te session ömrünü yeniler
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

LOGGING = {
    'version': 1,

    # 🔥 Mevcut tüm logger'ları sustur
    'disable_existing_loggers': True,

    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} - {message}',
            'style': '{',
        },
    },

    'handlers': {
        # ✅ SADECE DOSYA
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django.log'),
            'formatter': 'verbose',
        },
    },

    # 🔥 ROOT LOGGER → console YOK
    'root': {
        'handlers': ['file'],
        'level': 'WARNING',
    },

    'loggers': {
        # Django iç logları da dosyaya
        'django': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG:
    DB_PORT = '3307'
    DB_HOST = '127.0.0.1'
else:
    DB_PORT = '3306'
    DB_HOST = 'localhost'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'liftkeys_db',
        'USER': 'liftkeys_user',
        'PASSWORD': 'LiftSuskunKeys404.',
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'CONN_MAX_AGE': 600, # 🔥 KRİTİK AYAR: Bağlantıyı 10 dakika (600sn) canlı tut.
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
            # BURASI DEĞİŞTİ: MySQL 8.0 standardını ekledik
            'collation': 'utf8mb4_0900_ai_ci', 
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True

USE_I18N = True
WAGTAIL_I18N_ENABLED = True

LANGUAGES = [
    ('tr', 'Turkish'),
    ('en', 'English'),
    ('ar', 'Arabic'),
    ('ru', 'Russian'),
    ('fr', 'Français'),
    ('de', 'German'),
]
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]
WAGTAIL_CONTENT_LANGUAGES = LANGUAGES 

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# settings.py dosyasının en alt kısmına ekleyebilirsin

# Django E-posta (SMTP) Ayarları
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.liftkeys.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True  # Port 465 kullandığımız için SSL kullanıyoruz (TLS değil)
EMAIL_HOST_USER = 'info@liftkeys.com'
EMAIL_HOST_PASSWORD = 'Alperorhanproje17@'
DEFAULT_FROM_EMAIL = 'info@liftkeys.com'  # Maillerin kimden gittiğini gösteren adres


# settings.py dosyasının en alt satırına ekle:

# === DİL ÇEREZ AYARLARI ===
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = None  # Tarayıcı kapatıldığında dil seçimi sıfırlanır (Test için harika)
# Canlıya (Production) aldığında üstteki satırı silip alttakini açarsın:
# LANGUAGE_COOKIE_AGE = 365 * 24 * 60 * 60  # 1 yıl boyunca hatırla

LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_DOMAIN = None




# settings.py dosyasının en alt satırlarına ekle:

# === ROSETTA (ÇEVİRİ PANELİ) AYARLARI ===
ROSETTA_SHOW_AT_ADMIN_PANEL = True # Django admin panelinde Rosetta sekmesi oluşturur
ROSETTA_REQUIRE_AUTHENTICATION = True # Sadece giriş yapmış kullanıcılar görebilir